keyboard:
  matrix_positions:
    - [[1,1], [2,1], [3,1], [4,1], [5,1], [6,1],                  [13,1], [14,1], [15,1], [16,1], [17,1], [18,1]]
    - [[1,2], [2,2], [3,2], [4,2], [5,2], [6,2],                  [13,2], [14,2], [15,2], [16,2], [17,2], [18,2]]
    - [[1,3], [2,3], [3,3], [4,3], [5,3], [6,3],                  [13,3], [14,3], [15,3], [16,3], [17,3], [18,3]]
    - [                            [5,4], [6,4], [7,4],   [12,4], [13,4], [14,4]                                ]

  positions:
    - [[1,1], [2,1], [3,1], [4,1], [5,1], [6,1],                  [13,1], [14,1], [15,1], [16,1], [17,1], [18,1]]
    - [[1,2], [2,2], [3,2], [4,2], [5,2], [6,2],                  [13,2], [14,2], [15,2], [16,2], [17,2], [18,2]]
    - [[1,3], [2,3], [3,3], [4,3], [5,3], [6,3],                  [13,3], [14,3], [15,3], [16,3], [17,3], [18,3]]
    - [                            [5,4], [6,4], [7,4],   [12,4], [13,4], [14,4]                                ]

  hands:
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [                        Left, Left, Left,   Right, Right, Right                            ]

  fingers:
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer,                 Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer,                 Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer,                 Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [                             Thumb,   Thumb,   Thumb,   Thumb, Thumb,   Thumb,                              ]

  key_costs:
    - [25, 20, 14,  5, 14, 17,           17, 14,  5, 14, 20, 25]
    - [ 9,  5,  3,  3,  2,  6,            6,  2,  3,  3,  5,  9]
    - [20, 11, 22, 22, 10, 15,           15, 10, 22, 22, 11, 20]
    - [                 6,  3,  6,    6,  3,  6                ]

  unbalancing_positions:
    - [   2,   1.5, 0.1,   0, 0.1,   2,               2, 0.1,   0, 0.1,   1.5,   2]
    - [   1,     0,   0,   0,   0, 0.5,             0.5,   0,   0,   0,   0,     1]
    - [   2,     0,   0,   0,   0, 1.5,             1.5,   0,   0,   0,   0,     2]
    - [                         0,   0,   0,     0,   0,   0,                     ]

  symmetries:
    - [  9, 10, 11, 12, 13, 14,           14, 13, 12, 11, 10,  9]
    - [ 15, 16, 17, 18, 19, 20,           20, 19, 18, 17, 16, 15]
    - [ 21, 22, 23, 24, 25, 26,           26, 25, 24, 23, 22, 21]
    - [                 27, 28, 29,   29, 28, 27                ]



  plot_template: |2
                â”Œâ”€â”€â”€â”                         â”Œâ”€â”€â”€â”
            â”Œâ”€â”€â”€â”¤ {{3}} â”œâ”€â”€â”€â”¬â”€â”€â”€â”         â”Œâ”€â”€â”€â”¬â”€â”€â”€â”¤ {{8}} â”œâ”€â”€â”€â”
    â”Œâ”€â”€â”€â”¬â”€â”€â”€â”¤ {{2}} â”œâ”€â”€â”€â”¤ {{4}} â”‚ {{5}} â”‚         â”‚ {{6}} â”‚ {{7}} â”œâ”€â”€â”€â”¤ {{9}} â”œâ”€â”€â”€â”¬â”€â”€â”€â”
    â”‚ {{0}} â”‚ {{1}} â”œâ”€â”€â”€â”¤ {{15}} â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤         â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤ {{20}} â”œâ”€â”€â”€â”¤ {{10}} â”‚ {{11}} â”‚
    â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤ {{14}} â”œâ”€â”€â”€â”¤ {{16}} â”‚ {{17}} â”‚         â”‚ {{18}} â”‚ {{19}} â”œâ”€â”€â”€â”¤ {{21}} â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤
    â”‚ {{12}} â”‚ {{13}} â”œâ”€â”€â”€â”¤ {{27}} â”œâ”€â”â”€â”¼â”€â”€â”€â”¤         â”œâ”€â”€â”€â”¼â”€â”â”€â”¤ {{32}} â”œâ”€â”€â”€â”¤ {{22}} â”‚ {{23}} â”‚
    â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤ {{26}} â”œâ”€â”€â”€â”¤ {{28}} â”‚ {{29}} â”‚         â”‚ {{30}} â”‚ {{31}} â”œâ”€â”€â”€â”¤ {{33}} â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤
    â”‚ {{24}} â”‚ {{25}} â”œâ”€â”€â”€â”˜   â””â”€â”€â”€â”´â”€â”€â”€â”˜         â””â”€â”€â”€â”´â”€â”€â”€â”˜   â””â”€â”€â”€â”¤ {{34}} â”‚ {{35}} â”‚
    â””â”€â”€â”€â”´â”€â”€â”€â”˜       â”Œâ”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â” â”Œâ”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â”       â””â”€â”€â”€â”´â”€â”€â”€â”˜
                    â”‚ {{36}} â”‚ {{37}} â”‚ {{38}} â”‚ â”‚ {{39}} â”‚ {{40}} â”‚ {{41}} â”‚
                    â””â”€â”€â”€â”´â”€â”€â”€â”´â”€â”€â”€â”˜ â””â”€â”€â”€â”´â”€â”€â”€â”´â”€â”€â”€â”˜


  plot_template_short: |2
    {{0}}{{1}}{{2}}{{3}}{{4}}{{5}} {{6}}{{7}}{{8}}{{9}}{{10}}{{11}}
    â‡˜{{12}}{{13}}{{14}}{{15}}{{16}} {{17}}{{18}}{{19}}{{20}}{{21}}â‡˜
     {{22}}{{23}}{{24}}{{25}}{{26}} {{27}}{{28}}{{29}}{{30}}{{31}}

base_layout:
  keys:
    # Row 1
    - - ["x", "X", "Å¿", "âˆ’", "Î¾", "Î"]
      - ["v", "V", "â€¦", "â‡", "", "âˆš"]
      - ["l", "L", "_", "âŒ«", "Î»", "Î›"]
      - ["c", "C", "[", "â‡¡", "Ï‡", "â„‚"]
      - ["w", "W", "]", "âŒ¦", "Ï‰", "Î©"]
      - ["k", "K", "^", "â‡Ÿ", "Îº", "Ã—"]
      - ["h", "H", "!", "Â¡", "Ïˆ", "Î¨"]
      - ["g", "G", "<", "7", "Î³", "Î“"]
      - ["f", "F", ">", "8", "Ï†", "Î¦"]
      - ["q", "Q", "=", "9", "Ï•", "â„š"]
      - ["y", "Y", "&", "+", "Ï…", "âˆ‡"]
      - ["ÃŸ", "áº", "@", ".", "Ï‚", "âˆ˜"]
    # Row 2 (home row)
    - - ["â‡©"]
      - ["u", "U", "\\", "â‡±", "", "âŠ‚"]
      - ["i", "I", "/", "â‡ ", "Î¹", "âˆ«"]
      - ["a", "A", "{",  "â‡£", "Î±", "âˆ€"]
      - ["e", "E", "}", "â‡¢", "Îµ", "âˆƒ"]
      - ["o", "O", "*", "â‡²", "Î¿", "âˆˆ"]
      - ["s", "S", "?", "Â¿", "Ïƒ", "Î£"]
      - ["n", "N", "(", "4", "Î½", "â„•"]
      - ["r", "R", ")", "5", "Ï", "â„"]
      - ["t", "T", "-", "6", "Ï„", "âˆ‚"]
      - ["d", "D", ":", ",", "Î´", "Î”"]
      - ["â‡˜"]
    # Row 3
    - - [""]
      - ["Ã¼", "Ãœ", "#", "", "", "âˆª"]
      - ["Ã¶", "Ã–", "$", "\t", "Ïµ", "âˆ©"]
      - ["Ã¤", "Ã„", "|", "â€", "Î·", "â„µ"]
      - ["p", "P", "~", "\n", "Ï€", "Î "]
      - ["z", "Z", "`", "â†¶", "Î¶", "â„¤"]
      - ["b", "B", "+", ":", "Î²", "â‡"]
      - ["m", "M", "%", "1", "Î¼", "â‡”"]
      - [",", "â€“", '"', "2", "Ï±", "â‡’"]
      - [".", "â€¢", "'", "3", "Ï‘", "â†¦"]
      - ["j", "J", ";", ";", "Î¸", "Î˜"]
      - [""]
    # Row 4, containing the spacebar
    - - ["â‡š"]
      - ["â‡§"]
      - ["\t"]
      - ["â"]
      - [" ", " ", " ", "0", "Â ", "â€¯"]
      - ["â‡™"]
      - [""]
      - [""]

  fixed_keys:
    - [ false, false, false, false, false, false,                  false, false, false, false, false, false]
    - [  true, false, false, false, false, false,                  false, false, false, false, false,  true]
    - [  true, false, false, false, false, false,                  false, false, false, false, false,  true]
    - [                              true,  true,  true,    true,  true,  true                     ]

  fixed_layers: [2, 3]

  modifiers:
    - Left: ["â‡§"]
      Right: ["â‡§"]
    - Left: ["â‡©"]
      Right: ["â‡˜"]
    - Left: ["â‡š"]
      Right: ["â‡™"]
    - Left: ["â‡§", "â‡š"]
      Right: ["â‡§", "â‡™"]
    - Left: ["â‡©", "â‡š"]
      Right: ["â‡˜", "â‡™"]

  layer_costs: [0, 20, 9, 16, 29, 25]
