keyboard:
  matrix_positions:
    - [[1,0], [2,0], [3,0], [4,0], [5,0], [6,0],        [13,0], [14,0], [15,0], [16,0], [17,0], [18,0]]
    - [[1,1], [2,1], [3,1], [4,1], [5,1], [6,1],        [13,1], [14,1], [15,1], [16,1], [17,1], [18,1]]
    - [[1,2], [2,2], [3,2], [4,2], [5,2], [6,2],        [13,2], [14,2], [15,2], [16,2], [17,2], [18,2]]
    - [[1,3], [2,3], [3,3], [4,3], [5,3], [6,3],        [13,3], [14,3], [15,3], [16,3], [17,3], [18,3]]
    - [[1,4], [2,4], [3,4], [4,4], [5,4], [6,4], [9,4], [13,4], [14,4], [15,4], [16,4], [17,4], [18,4]]

  positions:
    - [[1,0], [2,0], [3,0], [4,0], [5,0], [6,0],        [13,0], [14,0], [15,0], [16,0], [17,0], [18,0]]
    - [[1,1], [2,1], [3,1], [4,1], [5,1], [6,1],        [13,1], [14,1], [15,1], [16,1], [17,1], [18,1]]
    - [[1,2], [2,2], [3,2], [4,2], [5,2], [6,2],        [13,2], [14,2], [15,2], [16,2], [17,2], [18,2]]
    - [[1,3], [2,3], [3,3], [4,3], [5,3], [6,3],        [13,3], [14,3], [15,3], [16,3], [17,3], [18,3]]
    - [[1,4], [2,4], [3,4], [4,4], [5,4], [6,4], [9,4], [13,4], [14,4], [15,4], [16,4], [17,4], [18,4]]

  hands:
    - [Left, Left, Left, Left, Left, Left,        Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,        Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,        Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,        Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left, Right, Right, Right, Right, Right, Right, Right]

  fingers:
    - [Pinky, Pinky, Ring,  Middle, Index, Index,        Index, Index, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Index, Index,        Index, Index, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Index, Index,        Index, Index, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Index, Index,        Index, Index, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Thumb,  Thumb,   Thumb,   Thumb, Thumb,   Thumb,   Thumb,  Ring,  Pinky, Pinky]

  key_costs:
    - [70, 60, 50, 50, 50, 60,     60, 50, 50, 50, 60, 70]
    - [20, 17, 15,  5, 12, 17,     17, 12,  5, 15, 17, 20]
    - [ 9,  5,  3,  3,  3,  6,      6,  3,  3,  3,  5,  9]
    - [20, 11, 22, 22, 10, 15,     15, 10, 22, 22, 11, 20]
    - [30, 25, 20,  4,  3,  3,  3,  3,  3,  4, 20, 25, 30]

  unbalancing_positions:
    - [[-2,  3], [0, 2.5], [0, 1.5], [0,  1], [0, 1.5], [1,    2],            [-1,    2], [0, 1.5], [0, 1], [0, 1.5], [0, 2.5], [2,  3]]
    - [[-2,  2], [0, 1.5], [0, 0.5], [0,  0], [0, 0.5], [1,    1],            [-1,    1], [0, 0.5], [0, 0], [0, 0.5], [0, 1.5], [2,  2]]
    - [[-1,  0], [0,   0], [0,   0], [0,  0], [0,   0], [0.5,  0],            [-0.5,  0], [0,   0], [0, 0], [0,   0], [0,   0], [1,  0]]
    - [[-2, -2], [0,   0], [0,   0], [0,  0], [0,   0], [1,   -1],            [-1,   -1], [0,   0], [0, 0], [0,   0], [0,   0], [2, -2]]
    - [[-3, -3], [-2, -2], [-1.5,-1],[-1,-1], [0,   0], [0,    0],   [0, 0],  [0,   0],   [0,   0], [1,-1], [1.5,-1], [2,  -2], [3, -3]]

  symmetries:
    - [  1,  2,  3,  4,  5,  6,      6,  5,  4,  3,  2,  1]
    - [  9, 10, 11, 12, 13, 14,     14, 13, 12, 11, 10,  9]
    - [ 15, 16, 17, 18, 19, 20,     20, 19, 18, 17, 16, 15]
    - [ 21, 22, 23, 24, 25, 26,     26, 25, 24, 23, 22, 21]
    - [ 27, 28, 29, 30, 31, 32, 33, 32, 31, 30, 29, 28, 27]



  plot_template: |2
                  ┌───┐                       ┌───┐
              ┌───┤ {{3}} ├───┬───┐       ┌───┬───┤ {{8}} ├───┐
    ┌─────┬───┤ {{2}} ├───┤ {{4}} │ {{5}} │       │ {{6}} │ {{7}} ├───┤ {{9}} ├───┬─────┐
    │  {{0}}  │ {{1}} ├───┤ {{15}} ├───┼───┤       ├───┼───┤ {{20}} ├───┤ {{10}} │  {{11}}  │
    ├─────┼───┤ {{14}} ├───┤ {{16}} │ {{17}} │       │ {{18}} │ {{19}} ├───┤ {{21}} ├───┼─────┤
    │  {{12}}  │ {{13}} ├───┤ {{27}} ├───┼───┤       ├───┼───┤ {{32}} ├───┤ {{22}} │  {{23}}  │
    ├─────┼───┤ {{26}} ├───┤ {{28}} │ {{29}} │       │ {{30}} │ {{31}} ├───┤ {{33}} ├───┼─────┤
    │  {{24}}  │ {{25}} ├───┤ {{39}} ├─━─┼───┤       ├───┼─━─┤ {{44}} ├───┤ {{34}} │  {{35}}  │
    ├─────┼───┤ {{38}} ├───┤ {{40}} │ {{41}} │       │ {{42}} │ {{43}} ├───┤ {{45}} ├───┼─────┤
    │  {{36}}  │ {{37}} ├───┘   └───┴───┘       └───┴───┘   └───┤ {{46}} │  {{47}}  │
    ├─────┼───┼───┬───┬───┬───┐ ┌───┐ ┌───┬───┬───┬───┼───┼─────┤
    │  {{48}}  │ {{49}} │ {{50}} │ {{51}} │ {{52}} │ {{53}} │ │ {{54}} │ │ {{55}} │ {{56}} │ {{57}} │ {{58}} │ {{59}} │  {{60}}  │
    └─────┴───┴───┴───┴───┴───┘ └───┘ └───┴───┴───┴───┴───┴─────┘


  plot_template_short: |2
    {{0}}{{1}}{{2}}{{3}}{{4}}{{5}} {{6}}{{7}}{{8}}{{9}}{{10}}{{11}}
    ⇘{{12}}{{13}}{{14}}{{15}}{{16}} {{17}}{{18}}{{19}}{{20}}{{21}}⇘
     {{22}}{{23}}{{24}}{{25}}{{26}} {{27}}{{28}}{{29}}{{30}}{{31}}

base_layout:
  keys:
    # Row 0 (number row)
    - - ["1", "°", "¹", "ª", "₁", "¬"]
      - ["2", "§", "²", "º", "₂", "∨"]
      - ["3", "ℓ", "³", "№", "₃", "∧"]
      - ["4", "»", "›", "", "♀", "⊥"]
      - ["5", "«", "‹", "·", "♂", "∡"]
      - ["6", "$", "¢", "£", "⚥", "∥"]
      - ["7", "€", "¥", "¤", "ϰ", "→"]
      - ["8", "„", "‚", "⇥", "⟨", "∞"]
      - ["9", "“", "‘", "/", "⟩", "∝"]
      - ["0", "”", "’", "*", "₀", "∅"]
      - ["^", "ˇ", "↻", "˙", "˞", "̣"]
      - ["-", "—", "-", "‑", "­", ""]
    # Row 1
    - - ["x", "X", "ſ", "−", "ξ", "Ξ"]
      - ["v", "V", "…", "⇞", "", "√"]
      - ["l", "L", "_", "⌫", "λ", "Λ"]
      - ["c", "C", "[", "⇡", "χ", "ℂ"]
      - ["w", "W", "]", "⌦", "ω", "Ω"]
      - ["k", "K", "^", "⇟", "κ", "×"]
      - ["h", "H", "!", "¡", "ψ", "Ψ"]
      - ["g", "G", "<", "7", "γ", "Γ"]
      - ["f", "F", ">", "8", "φ", "Φ"]
      - ["q", "Q", "=", "9", "ϕ", "ℚ"]
      - ["y", "Y", "&", "+", "υ", "∇"]
      - ["ß", "ẞ", "@", ".", "ς", "∘"]
    # Row 2 (home row)
    - - ["⇩"]
      - ["u", "U", "\\", "⇱", "", "⊂"]
      - ["i", "I", "/", "⇠", "ι", "∫"]
      - ["a", "A", "{",  "⇣", "α", "∀"]
      - ["e", "E", "}", "⇢", "ε", "∃"]
      - ["o", "O", "*", "⇲", "ο", "∈"]
      - ["s", "S", "?", "¿", "σ", "Σ"]
      - ["n", "N", "(", "4", "ν", "ℕ"]
      - ["r", "R", ")", "5", "ρ", "ℝ"]
      - ["t", "T", "-", "6", "τ", "∂"]
      - ["d", "D", ":", ",", "δ", "Δ"]
      - ["⇘"]
    # Row 3
    - - ["⇧"]
      - ["ü", "Ü", "#", "", "", "∪"]
      - ["ö", "Ö", "$", "\t", "ϵ", "∩"]
      - ["ä", "Ä", "|", "⎀", "η", "ℵ"]
      - ["p", "P", "~", "\n", "π", "Π"]
      - ["z", "Z", "`", "↶", "ζ", "ℤ"]
      - ["b", "B", "+", ":", "β", "⇐"]
      - ["m", "M", "%", "1", "μ", "⇔"]
      - [",", "–", '"', "2", "ϱ", "⇒"]
      - [".", "•", "'", "3", "ϑ", "↦"]
      - ["j", "J", ";", ";", "θ", "Θ"]
      - ["⇗"]
    # Row 4, containing the spacebar
    - - [""]
      - [""]
      - [""]
      - ["⇚"]
      - [" ", " ", " ", "0", " ", " "]
      - ["♕"]
      - [""]
      - ["♔"]
      - [" ", " ", " ", "0", " ", " "]
      - ["⇙"]
      - [""]
      - [""]
      - ["♛"]

  fixed_keys:
    - [  true,  true,  true,  true,  true,  true,         true,  true,  true,  true,  true,  true]
    - [ false, false, false, false, false, false,        false, false, false, false, false, false]
    - [  true, false, false, false, false, false,        false, false, false, false, false,  true]
    - [  true, false, false, false, false, false,        false, false, false, false, false,  true]
    - [  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true]

  # starting from 0
  fixed_layers: [2, 3]

  modifiers:
    - Left: [[1,3]]
      Right: [[18,3]]
    - Left: [[1,2]]
      Right: [[18,2]]
    - Left: [[4,4]]
      Right: [[15,4]]
    - Left: [[1,3], [4,4]]
      Right: [[18,3], [15,4]]
    - Left: [[1,2], [4,4]]
      Right: [[18,2], [15,4]]
