keyboard:
  matrix_positions:
    - [[0,0],    [1,0], [2,0], [3,0], [4,0], [5,0], [6,0],   [13,0], [14,0], [15,0], [16,0], [17,0], [18,0], [19,0]]
    - [[0,1],          [2,1], [3,1], [4,1], [5,1], [6,1],   [13,1], [14,1], [15,1], [16,1], [17,1], [18,1], [19,1]]
    - [[0,2],            [2,2], [3,2], [4,2], [5,2], [6,2],   [13,2], [14,2], [15,2], [16,2], [17,2], [18,2], [19,2], [20,2]]
    - [[0,3],    [1,3],    [2,3], [3,3], [4,3], [5,3], [6,3],   [13,3], [14,3], [15,3], [16,3], [17,3], [18,3]]
    - [[0,4], [1,4], [2,4],                             [6,4],                        [16,4], [17,4], [18,4], [19,4]]

  positions:
    - [[   0,0],   [   1,0],   [   2,0],   [   3,0],   [   4,0],   [   5,0],   [   6,0],   [   7,0],   [   8,0],   [   9,0],   [   10,0],   [   11,0],   [   12,0],   [   13,0]]
    - [   [0.25,1],   [1.25,1],   [2.25,1],   [3.35,1],   [4.25,1],   [5.25,1],   [6.25,1],   [7.25,1],   [8.25,1],   [9.25,1],   [10.25,1],   [11.25,1],   [12.25,1]]
    - [      [ 0.5,2],   [ 1.5,2],   [ 2.5,2],   [ 3.5,2],   [ 4.5,2],   [ 5.5,2],   [ 6.5,2],   [ 7.5,2],   [ 8.5,2],   [ 9.5,2],   [ 10.5,2],   [ 11.5,2],   [ 12.5,2],   [ 13.5,2]]
    - [[   0,3],  [  1,3],  [1.75,3],   [2.75,3],   [3.75,3],   [4.75,3],   [5.75,3],   [6.75,3],   [7.75,3],   [8.75,3],   [ 9.75,3],   [10.75,3],   [11.75,3]]
    - [      [ 0.5,4],         [   2,4],   [   3,4],                                       [   7,4],                          [   10,4],   [ 11.5,4],   [   12,4],    [   13,4]]

  hands:
    - [Left,    Left, Left, Left, Left, Left, Left,   Right, Right, Right, Right, Right, Right, Right]
    - [Left,       Left, Left, Left, Left, Left,   Right, Right, Right, Right, Right, Right, Right]
    - [Left,         Left, Left, Left, Left, Left,   Right, Right, Right, Right, Right, Right, Right, Right]
    - [Left,    Left,  Left, Left, Left, Left, Left,   Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left,                     Right,                      Right, Right, Right, Right]

  fingers:
    - [Pinky,    Pinky, Pinky, Ring, Middle, Pointer, Pointer,   Pointer, Pointer, Middle, Ring, Pinky, Pinky, Pinky]
    - [Pinky,       Pinky, Ring, Middle, Pointer, Pointer,   Pointer, Pointer, Middle, Ring, Pinky, Pinky, Pinky]
    - [Pinky,          Pinky, Ring, Middle, Pointer, Pointer,   Pointer, Pointer, Middle, Ring, Pinky, Pinky, Pinky, Pinky]
    - [Pinky,    Pinky,   Pinky, Ring, Middle, Pointer, Pointer,   Pointer, Pointer, Middle, Ring, Pinky, Pinky]
    - [Pinky, Ring, Thumb,                          Thumb,                      Thumb, Middle, Ring, Pinky]

  key_costs:
    - [80,   70, 60, 50, 50, 50, 60,   60, 50, 50, 50, 60, 70, 80]
    - [24,      16, 10,  5, 12, 17,   20, 13,  5,  9, 11, 20, 36]
    - [ 9,         5,  3,  3,  3,  6,    6,  3,  3,  3,  5,  9, 30,  6]
    - [20,   16,    19, 22, 22,  9, 30,   10,  8, 20, 20, 17, 19]
    - [ 0,  0,  0,              3,               7,  0,  0,  0]

  unbalancing_positions:
    - [  2,      2,    2,   0,   0,   0,   0,     0,   0,   0,   2,   2,   2,   2]
    - [  2,           1,   0,   0, 0.1,   2,     2, 0.1,   0,   0,   1,   2, 2.5]
    - [  1,             0,   0,   0,   0,   1,     1,   0,   0,   0,   0,   1,   2,   2]
    - [  2,      0,       0, 0.5, 0.5,   0,   2,    0.5,   0, 0.5, 0.5,   0,   2]
    - [  3,   0,   0,                       0,                        0,   0,   0,   3]

  symmetries:
    - [  1,       2,   3,   4,   5,   6,   7,    7,   6,   5,   4,   3,   2,   1]
    - [  9,          10,  11,  12,  13,  14,    14,  13,  12,  11,  10,   9,  15]
    - [ 16,            17,  18,  19,  20,  21,    21,  20,  19,  18,  17,  16,  22,  23]
    - [ 24,      25,     26,  27,  28,  29,  30,     30,  29,  28,  27,  26,  24]
    - [ 31,  32,  33,                      34,                       35,  36,  37,  38]


  plot_template: |2
    â”Œâ”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”
    â”‚ {{0}} â”‚ {{1}} â”‚ {{2}} â”‚ {{3}} â”‚ {{4}} â”‚ {{5}} â”‚ {{6}} â”‚ {{7}} â”‚ {{8}} â”‚ {{9}} â”‚ {{10}} â”‚ {{11}} â”‚ {{12}} â”‚ {{13}}    â”‚
    â”œâ”€â”€â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”€â”€â”€â”¤
    â”‚   {{14}} â”‚ {{15}} â”‚ {{16}} â”‚ {{17}} â”‚ {{18}} â”‚ {{19}} â”‚ {{20}} â”‚ {{21}} â”‚ {{22}} â”‚ {{23}} â”‚ {{24}} â”‚ {{25}} â”‚ {{26}} â”‚ Retâ”‚
    â”œâ”€â”€â”€â”€â”€â”´â”¬â”€â”€â”´â”¬â”€â”€â”´â”¬â”€â”€â”´â”¬â”€â”€â”´â”¬â”€â”€â”´â”¬â”€â”€â”´â”¬â”€â”€â”´â”¬â”€â”€â”´â”¬â”€â”€â”´â”¬â”€â”€â”´â”¬â”€â”€â”´â”¬â”€â”€â”´â”   â”‚
    â”‚    {{27}} â”‚ {{28}} â”‚ {{29}} â”‚ {{30}} â”‚ {{31}} â”‚ {{32}} â”‚ {{33}} â”‚ {{34}} â”‚ {{35}} â”‚ {{36}} â”‚ {{37}} â”‚ {{38}} â”‚ {{39}} â”‚ {{40}} â”‚
    â”œâ”€â”€â”€â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”¯â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”¯â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”¬â”€â”´â”€â”€â”€â”´â”€â”€â”€â”¤
    â”‚  {{41}} â”‚ {{42}} â”‚ {{43}} â”‚ {{44}} â”‚ {{45}} â”‚ {{46}} â”‚ {{47}} â”‚ {{48}} â”‚ {{49}} â”‚ {{50}} â”‚ {{51}} â”‚ {{52}} â”‚    {{53}}    â”‚
    â”œâ”€â”€â”€â”€â”¼â”€â”€â”€â”´â”¬â”€â”€â”´â”€â”¬â”€â”´â”€â”€â”€â”´â”€â”€â”€â”´â”€â”€â”€â”´â”€â”€â”€â”´â”€â”€â”€â”´â”€â”¬â”€â”´â”€â”€â”¬â”´â”€â”€â”€â”¼â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”¤
    â”‚  {{54}} â”‚ {{55}}  â”‚ {{56}}  â”‚           {{57}}           â”‚  {{58}} â”‚  {{59}} â”‚  {{60}} â”‚  {{61}} â”‚
    â””â”€â”€â”€â”€â”´â”€â”€â”€â”€â”´â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”´â”€â”€â”€â”€â”´â”€â”€â”€â”€â”´â”€â”€â”€â”€â”˜


  plot_template_short: |2
    {{0}}{{1}}{{2}}{{3}}{{4}} {{5}}{{6}}{{7}}{{8}}{{9}}{{10}}{{11}}
    {{12}}{{13}}{{14}}{{15}}{{16}} {{17}}{{18}}{{19}}{{20}}{{21}}â‡˜
    {{22}}{{23}}{{24}}{{25}}{{26}} {{27}}{{28}}{{29}}{{30}}{{31}}

base_layout:
  keys:
    # Row 0 (number row)
    - - ["^", "Ë‡", "â†»", "Ë™", "Ë", "Ì£"]
      - ["1", "Â°", "Â¹", "Âª", "â‚", "Â¬"]
      - ["2", "Â§", "Â²", "Âº", "â‚‚", "âˆ¨"]
      - ["3", "â„“", "Â³", "â„–", "â‚ƒ", "âˆ§"]
      - ["4", "Â»", "â€º", "", "â™€", "âŠ¥"]
      - ["5", "Â«", "â€¹", "Â·", "â™‚", "âˆ¡"]
      - ["6", "$", "Â¢", "Â£", "âš¥", "âˆ¥"]
      - ["7", "â‚¬", "Â¥", "Â¤", "Ï°", "â†’"]
      - ["8", "â€", "â€š", "â‡¥", "âŸ¨", "âˆ"]
      - ["9", "â€œ", "â€˜", "/", "âŸ©", "âˆ"]
      - ["0", "â€", "â€™", "*", "â‚€", "âˆ…"]
      - ["-", "â€”", "-", "â€‘", "Â­", ""]
      - ["`", "Â¸", "Â°", "Â¨", "", "Â¯"]
      - ["â†"]
    # Row 1
    - - ["â‡¥"]
      - ["x", "X", "â€¦", "â‡", "Î¾", "Î"]
      - ["v", "V", "_", "âŒ«", "", "âˆš"]
      - ["l", "L", "[", "â‡¡", "Î»", "Î›"]
      - ["c", "C", "]", "âŒ¦", "Ï‡", "â„‚"]
      - ["w", "W", "^", "â‡Ÿ", "Ï‰", "Î©"]
      - ["k", "K", "!", "Â¡", "Îº", "Ã—"]
      - ["h", "H", "<", "7", "Ïˆ", "Î¨"]
      - ["g", "G", ">", "8", "Î³", "Î“"]
      - ["f", "F", "=", "9", "Ï†", "Î¦"]
      - ["q", "Q", "&", "+", "Ï•", "â„š"]
      - ["y", "Y", "@", ".", "Ï…", "âˆ‡"]
      - ["ÃŸ", "áº", "Å¿", "âˆ’", "Ï‚", "âˆ˜"]
    # Row 2 (home row)
    - - ["â‡©"]
      - ["u", "U", "\\", "â‡±", "", "âŠ‚"]
      - ["i", "I", "/", "â‡ ", "Î¹", "âˆ«"]
      - ["a", "A", "{",  "â‡£", "Î±", "âˆ€"]
      - ["e", "E", "}", "â‡¢", "Îµ", "âˆƒ"]
      - ["o", "O", "*", "â‡²", "Î¿", "âˆˆ"]
      - ["s", "S", "?", "Â¿", "Ïƒ", "Î£"]
      - ["n", "N", "(", "4", "Î½", "â„•"]
      - ["r", "R", ")", "5", "Ï", "â„"]
      - ["t", "T", "-", "6", "Ï„", "âˆ‚"]
      - ["d", "D", ":", ",", "Î´", "Î”"]
      - ["â‡˜"]
      - ["Â´", "~", "/", "Ë", "", "Ë˜"]
      - ["\n"]
    # Row 3
    - - ["â‡§"]
      - ["â‡š"]
      - ["Ã¼", "Ãœ", "#", "", "", "âˆª"]
      - ["Ã¶", "Ã–", "$", "\t", "Ïµ", "âˆ©"]
      - ["Ã¤", "Ã„", "|", "â€", "Î·", "â„µ"]
      - ["p", "P", "~", "\n", "Ï€", "Î "]
      - ["z", "Z", "`", "â†¶", "Î¶", "â„¤"]
      - ["b", "B", "+", ":", "Î²", "â‡"]
      - ["m", "M", "%", "1", "Î¼", "â‡”"]
      - [",", "â€“", '"', "2", "Ï±", "â‡’"]
      - [".", "â€¢", "'", "3", "Ï‘", "â†¦"]
      - ["j", "J", ";", ";", "Î¸", "Î˜"]
      - ["â‡—"]
    # Row 4, containing the spacebar
    - - ["â™•"]
      - [""]
      - ["â™”"]
      - [" ", " ", " ", "0", "Â ", "â€¯"]
      - ["â‡™"]
      - [""]
      - [""]
      - ["â™›"]

  fixed_keys:
    - [ true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true]
    - [ true, false, false, false, false, false, false, false, false, false, false, false, false]
    - [ true, false, false, false, false, false, false, false, false, false, false,  true,  true,  true]
    - [ true,  true, false, false, false, false, false, false, false, false, false, false,  true]
    - [ true,  true,  true,                       true,                       true,  true,  true,  true]

  fixed_layers: [2, 3]

  modifiers:
    - Left: [[0,3]]
      Right: [[18,3]]
    - Left: [[0,2]]
      Right: [[18,2]]
    - Left: [[1,3]]
      Right: [[16,4]]
    - Left: [[0,3], [1,3]]
      Right: [[18,3], [16,4]]
    - Left: [[0,2], [1,3]]
      Right: [[18,2], [16,4]]
