keyboard:
  matrix_positions:
    - [[0,0], [1,0], [2,0], [3,0], [4,0], [5,0],                 [8,0], [9,0], [10,0], [11,0], [12,0], [13,0]]
    - [[0,1], [1,1], [2,1], [3,1], [4,1], [5,1],                 [8,1], [9,1], [10,1], [11,1], [12,1], [13,1]]
    - [[0,2], [1,2], [2,2], [3,2], [4,2], [5,2],                 [8,2], [9,2], [10,2], [11,2], [12,2], [13,2]]
    - [                            [4,3], [5,3], [6,3],   [7,3], [8,3], [9,3], [10,3]                        ]

  positions:
    - [[0,0], [1,0], [2,0], [3,0], [4,0], [5,0],                 [8,0], [9,0], [10,0], [11,0], [12,0], [13,0]]
    - [[0,1], [1,1], [2,1], [3,1], [4,1], [5,1],                 [8,1], [9,1], [10,1], [11,1], [12,1], [13,1]]
    - [[0,2], [1,2], [2,2], [3,2], [4,2], [5,2],                 [8,2], [9,2], [10,2], [11,2], [12,2], [13,2]]
    - [                            [4,3], [5,3], [6,3],   [7,3], [8,3], [9,3], [10,3]                        ]

  hands:
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [                        Left, Left, Left,   Right, Right, Right, Right                     ]

  fingers:
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer,                 Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer,                 Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Pointer, Pointer,                 Pointer, Pointer, Middle, Ring,  Pinky, Pinky]
    - [                             Thumb,   Thumb,   Thumb,   Thumb, Thumb,   Thumb,                              ]

  key_costs:
    - [20, 17,  9,  5, 12, 17,           17, 12,  5,  9, 17, 20]
    - [ 9,  5,  3,  3,  3,  6,            6,  3,  3,  3,  5,  9]
    - [20, 11, 22, 22, 10, 15,           15, 10, 22, 22, 11, 20]
    - [                 6,  3,  6,    6,  3,  6                ]

  unbalancing_positions:
    - [   2,   1,   0,   0, 0.1,   2,               2, 0.1,   0,   0,   1,   2]
    - [   1,   0,   0,   0,   0,   1,               1,   0,   0,   0,   0,   1]
    - [   2,   0,   0,   0,   0, 1.5,             1.5,   0,   0,   0,   0,   2]
    - [                       0,   0,   0,     0,   0,   0,                   ]

  symmetries:
    - [  9, 10, 11, 12, 13, 14,           14, 13, 12, 11, 10,  9]
    - [ 15, 16, 17, 18, 19, 20,           20, 19, 18, 17, 16, 15]
    - [ 21, 22, 23, 24, 25, 26,           26, 25, 24, 23, 22, 21]
    - [                 27, 28, 29,   29, 28, 27                ]



  plot_template: |2
                â”Œâ”€â”€â”€â”                         â”Œâ”€â”€â”€â”
            â”Œâ”€â”€â”€â”¤ {{3}} â”œâ”€â”€â”€â”¬â”€â”€â”€â”         â”Œâ”€â”€â”€â”¬â”€â”€â”€â”¤ {{8}} â”œâ”€â”€â”€â”
    â”Œâ”€â”€â”€â”¬â”€â”€â”€â”¤ {{2}} â”œâ”€â”€â”€â”¤ {{4}} â”‚ {{5}} â”‚         â”‚ {{6}} â”‚ {{7}} â”œâ”€â”€â”€â”¤ {{9}} â”œâ”€â”€â”€â”¬â”€â”€â”€â”
    â”‚ {{0}} â”‚ {{1}} â”œâ”€â”€â”€â”¤ {{15}} â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤         â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤ {{20}} â”œâ”€â”€â”€â”¤ {{10}} â”‚ {{11}} â”‚
    â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤ {{14}} â”œâ”€â”€â”€â”¤ {{16}} â”‚ {{17}} â”‚         â”‚ {{18}} â”‚ {{19}} â”œâ”€â”€â”€â”¤ {{21}} â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤
    â”‚ {{12}} â”‚ {{13}} â”œâ”€â”€â”€â”¤ {{27}} â”œâ”€â”â”€â”¼â”€â”€â”€â”¤         â”œâ”€â”€â”€â”¼â”€â”â”€â”¤ {{32}} â”œâ”€â”€â”€â”¤ {{22}} â”‚ {{23}} â”‚
    â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤ {{26}} â”œâ”€â”€â”€â”¤ {{28}} â”‚ {{29}} â”‚         â”‚ {{30}} â”‚ {{31}} â”œâ”€â”€â”€â”¤ {{33}} â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤
    â”‚ {{24}} â”‚ {{25}} â”œâ”€â”€â”€â”˜   â””â”€â”€â”€â”´â”€â”€â”€â”˜         â””â”€â”€â”€â”´â”€â”€â”€â”˜   â””â”€â”€â”€â”¤ {{34}} â”‚ {{35}} â”‚
    â””â”€â”€â”€â”´â”€â”€â”€â”˜       â”Œâ”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â” â”Œâ”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â”       â””â”€â”€â”€â”´â”€â”€â”€â”˜
                    â”‚ {{36}} â”‚ {{37}} â”‚ {{38}} â”‚ â”‚ {{39}} â”‚ {{40}} â”‚ {{41}} â”‚
                    â””â”€â”€â”€â”´â”€â”€â”€â”´â”€â”€â”€â”˜ â””â”€â”€â”€â”´â”€â”€â”€â”´â”€â”€â”€â”˜


  plot_template_short: |2
    {{0}}{{1}}{{2}}{{3}}{{4}}{{5}} {{6}}{{7}}{{8}}{{9}}{{10}}{{11}}
    â‡˜{{12}}{{13}}{{14}}{{15}}{{16}} {{17}}{{18}}{{19}}{{20}}{{21}}â‡˜
     {{22}}{{23}}{{24}}{{25}}{{26}} {{27}}{{28}}{{29}}{{30}}{{31}}

base_layout:
  keys:
    # Reihe 1
    - - ["x", "X", "â€¦", "â‡", "Î¾", "Î"]
      - ["v", "V", "_", "âŒ«", "", "âˆš"]
      - ["l", "L", "[", "â‡¡", "Î»", "Î›"]
      - ["c", "C", "]", "âŒ¦", "Ï‡", "â„‚"]
      - ["w", "W", "^", "â‡Ÿ", "Ï‰", "Î©"]
      - ["k", "K", "!", "Â¡", "Îº", "Ã—"]
      - ["h", "H", "<", "7", "Ïˆ", "Î¨"]
      - ["g", "G", ">", "8", "Î³", "Î“"]
      - ["f", "F", "=", "9", "Ï†", "Î¦"]
      - ["q", "Q", "&", "+", "Ï•", "â„š"]
      - ["y", "Y", "@", ".", "Ï…", "âˆ‡"]
      - ["ÃŸ", "áº", "Å¿", "âˆ’", "Ï‚", "âˆ˜"]
    # Reihe 2
    - - ["â‡©"]
      - ["u", "U", "\\", "â‡±", "", "âŠ‚"]
      - ["i", "I", "/", "â‡ ", "Î¹", "âˆ«"]
      - ["a", "A", "{",  "â‡£", "Î±", "âˆ€"]
      - ["e", "E", "}", "â‡¢", "Îµ", "âˆƒ"]
      - ["o", "O", "*", "â‡²", "Î¿", "âˆˆ"]
      - ["s", "S", "?", "Â¿", "Ïƒ", "Î£"]
      - ["n", "N", "(", "4", "Î½", "â„•"]
      - ["r", "R", ")", "5", "Ï", "â„"]
      - ["t", "T", "-", "6", "Ï„", "âˆ‚"]
      - ["d", "D", ":", ",", "Î´", "Î”"]
      - ["â‡˜"]
    # Reihe 3
    - - [""]
      - ["Ã¼", "Ãœ", "#", "", "", "âˆª"]
      - ["Ã¶", "Ã–", "$", "\t", "Ïµ", "âˆ©"]
      - ["Ã¤", "Ã„", "|", "â€", "Î·", "â„µ"]
      - ["p", "P", "~", "\n", "Ï€", "Î "]
      - ["z", "Z", "`", "â†¶", "Î¶", "â„¤"]
      - ["b", "B", "+", ":", "Î²", "â‡"]
      - ["m", "M", "%", "1", "Î¼", "â‡”"]
      - [",", "â€“", '"', "2", "Ï±", "â‡’"]
      - [".", "â€¢", "'", "3", "Ï‘", "â†¦"]
      - ["j", "J", ";", ";", "Î¸", "Î˜"]
      - [""]
    # Reihe 4 mit Leertaste
    - - ["â‡š"]
      - [" ", " ", " ", "0", "Â ", "â€¯"]
      - ["â™•"]
      - ["â‡§"]
      - ["â"]
      - ["â‡™"]

  fixed_keys:
    - [ false, false, false, false, false, false,        false, false, false, false, false, false]
    - [  true, false, false, false, false, false,        false, false, false, false, false,  true]
    - [  true, false, false, false, false, false,        false, false, false, false, false,  true]
    - [  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true]

  fixed_layers: [2, 3]

  modifiers:
    - Left: ["â‡§"]
      Right: ["â‡§"]
    - Left: ["â‡©"]
      Right: ["â‡˜"]
    - Left: ["â‡š"]
      Right: ["â‡™"]
    - Left: ["â‡§", "â‡š"]
      Right: ["â‡§", "â‡™"]
    - Left: ["â‡©", "â‡š"]
      Right: ["â‡˜", "â‡™"]

  layer_costs: [0, 20, 9, 16, 29, 25]
