# Initial temperature.
# Set to 0 if a greedy algorithm is preferred.
# If you want the optimizer to calculate the starting-temperature for you, set init_temp to null.
init_temp: 100

# Swap out this many keys-pairs on every iteration.
# In Simulated Annealing it's best to keep the variation between
# iterations low. Thus, one single swap may be best.
key_switches: 1

# Stop if there was no accepted solution after this many iterations
stall_accepted: 4000

# Set maximum number of iterations.
# At first iterations might take a while, but eventually they will speed up due to caching.
max_iters: 50000
